#!/bin/bash

. $HOME/.bin/restic_common
export RESTIC_PASSWORD="${RESTIC_PASSWORD}"

info "Starting backup"
restic -r $RESTIC_REPOSITORY unlock
restic --cache-dir $CACHE_DIR -r $RESTIC_REPOSITORY backup $BACKUP_PATHS $BACKUP_EXCLUDES
