#!/bin/bash

. $HOME/.bin/restic_common
export RESTIC_PASSWORD="${RESTIC_PASSWORD}"
export PATH="$HOME/.local/bin:$PATH"

info "Starting backup"
restic -r ${RESTIC_REPOSITORY} unlock
restic --cache-dir ${CACHE_DIR} -r ${RESTIC_REPOSITORY} backup ${BACKUP_PATHS} --exclude ${BACKUP_EXCLUDES}

info "Forgetting snapshots"
restic --cache-dir ${CACHE_DIR} -r ${RESTIC_REPOSITORY} forget --keep-hourly ${KEEP_HOURS} --keep-daily ${KEEP_DAYS} --keep-weekly ${KEEP_WEEKS} --keep-monthly ${KEEP_WEEKS} --keep-yearly ${KEEP_YEARS}
